apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ printf "%s/%s" .Values.imageRegistry .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}

        - name: {{ .Values.backend.name }}
          image: {{ printf "%s/%s" .Values.imageRegistry .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}

        - name: {{ .Values.mongodb.name }}
          image: {{ printf "%s/%s" .Values.imageRegistry .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: {{ .Values.mongodbCredentials.usernameKey }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: {{ .Values.mongodbCredentials.passwordKey }}
