apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-client-service
spec:
  selector:
    app: todo-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: 5000
  type: LoadBalancer
