apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-client-service
spec:
  selector:
    app: todo-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000
  type: LoadBalancer
