appname: helm-taskmanager
imageRegistry: ghcr.io/lambrech-hsrt

frontend:
  name: helm-taskmanager-ui
  port: 80
  image: demo-app-frontend:latest

backend:
  name: helm-todo-backend
  port: 5000
  image: demo-app-backend:latest

mongodb:
  name: helm-mongodb
  port: 27017
  image: demo-app-mongodb:latest

mongodbCredentials:
  usernameKey: username
  passwordKey: password

