appname: helm-taskmanager
imageRegistry: ghcr.io/lambrech-hsrt

frontend:
  name: helm-taskmanager-ui
  port: 10000
  image: demo-app-frontend:latest

backend:
  name: helm-taskmanager-backend
  port: 8000
  image: demo-app-backend:latest

mongodb:
  name: helm-mongodb
  port: 27017
  image: demo-app-mongodb:latest

mongodbCredentials:
  usernameKey: YWRtaW4=
  passwordKey: YWRtaW4=

