apiVersion: apps/v1
kind: Deployment

metadata:
  name: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-taskmanager-app

  template:
    metadata:
      labels:
        app: helm-taskmanager-app

    spec:
      containers:
        - name: helm-taskmanager-ui
          image: ghcr.io/lambrech-hsrt/demo-app-frontend:latest
          ports:
            - containerPort: 80

        - name: helm-todo-backend
          image: ghcr.io/lambrech-hsrt/demo-app-backend:latest
          ports:
            - containerPort: 5000

        - name: helm-mongodb
          image: ghcr.io/lambrech-hsrt/demo-app-mongodb:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
